[[libsparseir]]
arch = "aarch64"
git-tree-sha1 = "71deb2ba5b548f781cf990c9edb2bbc4e3633f30"
os = "macos"

    [[libsparseir.download]]
    sha256 = "bc2fa2ad09cf041811a5d16bd0de75adce2060dffb6e5651ef105e2d9ae86ab6"
    url = "https://github.com/JuliaBinaryWrappers/libsparseir_jll.jl/releases/download/libsparseir-v0.7.3+0/libsparseir.v0.7.3.aarch64-apple-darwin.tar.gz"
[[libsparseir]]
arch = "aarch64"
git-tree-sha1 = "6c94c324972558791596720cdd764df51d6d4783"
libc = "glibc"
os = "linux"

    [[libsparseir.download]]
    sha256 = "0339375d15a5421933c59293067b89f6260942e5e6fd22b99ace4b5861989007"
    url = "https://github.com/JuliaBinaryWrappers/libsparseir_jll.jl/releases/download/libsparseir-v0.7.3+0/libsparseir.v0.7.3.aarch64-linux-gnu.tar.gz"
[[libsparseir]]
arch = "powerpc64le"
git-tree-sha1 = "15e6b588f03f7f40624dcbf3b50d7e521d957634"
libc = "glibc"
os = "linux"

    [[libsparseir.download]]
    sha256 = "bc45ca19a870ff1b201deb9e0f8d9ff6c7189f85f359b6940a90ba2ce4efa68a"
    url = "https://github.com/JuliaBinaryWrappers/libsparseir_jll.jl/releases/download/libsparseir-v0.7.3+0/libsparseir.v0.7.3.powerpc64le-linux-gnu.tar.gz"
[[libsparseir]]
arch = "x86_64"
git-tree-sha1 = "decc639c789f08996689fa97909dace2c084a8ff"
libc = "glibc"
os = "linux"

    [[libsparseir.download]]
    sha256 = "a5bbae9cb698f7fab60851d78ce048d14de69ae1d2324d953acdb82a961b60e3"
    url = "https://github.com/JuliaBinaryWrappers/libsparseir_jll.jl/releases/download/libsparseir-v0.7.3+0/libsparseir.v0.7.3.x86_64-linux-gnu.tar.gz"
[[libsparseir]]
arch = "x86_64"
git-tree-sha1 = "38a68554ba666807404e734e54558a91c672e07f"
os = "freebsd"

    [[libsparseir.download]]
    sha256 = "99db19b26ae675af91d86d1872e396016141d1cf8a30bcffea9d9452750b1a25"
    url = "https://github.com/JuliaBinaryWrappers/libsparseir_jll.jl/releases/download/libsparseir-v0.7.3+0/libsparseir.v0.7.3.x86_64-unknown-freebsd.tar.gz"
[[libsparseir]]
arch = "x86_64"
git-tree-sha1 = "d88c28738904b9579853c764bf3c2d2aa26159f3"
os = "windows"

    [[libsparseir.download]]
    sha256 = "92685e0b7ad2799958c0808da8cf1a8ceb965db651b36e630de706eb01c5c6f7"
    url = "https://github.com/JuliaBinaryWrappers/libsparseir_jll.jl/releases/download/libsparseir-v0.7.3+0/libsparseir.v0.7.3.x86_64-w64-mingw32.tar.gz"
