[[libsparseir]]
arch = "aarch64"
git-tree-sha1 = "2dce1a44e81441f0af384fe9cebcffd2daf351f0"
os = "macos"

    [[libsparseir.download]]
    sha256 = "3ab40ab7d8f5132fe8a9951a1433adb60e77c3632b64ce9ca1c22eb2638fb69d"
    url = "https://github.com/JuliaBinaryWrappers/libsparseir_jll.jl/releases/download/libsparseir-v0.8.0+0/libsparseir.v0.8.0.aarch64-apple-darwin.tar.gz"
[[libsparseir]]
arch = "aarch64"
git-tree-sha1 = "cc903ca7a1dffc27a46600fc15f4c725ef4eb5d9"
libc = "glibc"
os = "linux"

    [[libsparseir.download]]
    sha256 = "803d021fa1f97fdb98a5fa97b2b42f77c05f70c85426c06c67d2ae90a6ff27bd"
    url = "https://github.com/JuliaBinaryWrappers/libsparseir_jll.jl/releases/download/libsparseir-v0.8.0+0/libsparseir.v0.8.0.aarch64-linux-gnu.tar.gz"
[[libsparseir]]
arch = "powerpc64le"
git-tree-sha1 = "5b7aca4ef37907639ec3f770f29734a891887022"
libc = "glibc"
os = "linux"

    [[libsparseir.download]]
    sha256 = "d3e4a29b2991f042476ab467904b398a59244f6f44380e1ea62a44811fac03c5"
    url = "https://github.com/JuliaBinaryWrappers/libsparseir_jll.jl/releases/download/libsparseir-v0.8.0+0/libsparseir.v0.8.0.powerpc64le-linux-gnu.tar.gz"
[[libsparseir]]
arch = "x86_64"
git-tree-sha1 = "9e27bace26826b4be1c4dec0e4381505042b6293"
libc = "glibc"
os = "linux"

    [[libsparseir.download]]
    sha256 = "0a9dd76bfe006586802b1bc8c361f3073b997a795ad39b47794ea9b540fb9463"
    url = "https://github.com/JuliaBinaryWrappers/libsparseir_jll.jl/releases/download/libsparseir-v0.8.0+0/libsparseir.v0.8.0.x86_64-linux-gnu.tar.gz"
[[libsparseir]]
arch = "x86_64"
git-tree-sha1 = "774693e0d1f7bb8465699aba05f0a59235b7dee8"
os = "freebsd"

    [[libsparseir.download]]
    sha256 = "d161da4699818e4e1b94873d374838cad26c760391535f7c2dfa0e8712a96604"
    url = "https://github.com/JuliaBinaryWrappers/libsparseir_jll.jl/releases/download/libsparseir-v0.8.0+0/libsparseir.v0.8.0.x86_64-unknown-freebsd.tar.gz"
[[libsparseir]]
arch = "x86_64"
git-tree-sha1 = "b11545228e779acc7dad0b093191b37504dfb433"
os = "windows"

    [[libsparseir.download]]
    sha256 = "d5e9147e8f41009c7c5dc12a7964b41b1bd03f111f1d368453324987b33b93d5"
    url = "https://github.com/JuliaBinaryWrappers/libsparseir_jll.jl/releases/download/libsparseir-v0.8.0+0/libsparseir.v0.8.0.x86_64-w64-mingw32.tar.gz"
